### ISSUE TITLE
ITxModelClass selectSingle

### ISSUE THREAD

**Issue by luaneyed** [croquiscom/cormo#75]
`selectSingle`이 `IQuerySingle`랑 `IQueryArray`에만 있는데,
`select`처럼 `ITxModelClass`에도 있으면 `.where()` 같은 거 안 해도 돼서 좋겠습니다.

**Comment by sixmen** [comment]
모델 클래스에 쿼리 메소드들이 동일하게 모두 있는게 좋을까요? 메소드가 추가될때마다 모델에 넣는게 뭔가 아닌 것 같아서 어느 순간 이후로는 안 하고 있긴 합니다. `.query()` 로 명시적으로 쿼리 객체를 만드는게 지금 방향이긴 합니다

**Comment by luaneyed** [comment]
`.query()` 쪽이 옳은 방향인 것 같긴 하네요.
모델 메소드들 전부 deprecate (달아지면) 달고 언젠가 1.0 올리면 다 지울까요? 😆
